config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]

  resources :wikis

  resources :wikis, only: [] do
    resources :collaborators, only: [] do
      member do
        put :remove
      end
    end
  end

  devise_for :users

  resources :users, only: [] do
    member do
      put :downgrade
    end
  end

  get 'public_wikis' => 'wikis#public'
  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  #validates :user, uniqueness: {scope: :wiki}
  #validates :wiki, uniqueness: {scope: :user}

  #def self.update_collaborators(user)
     #return Collaboration.none if user.blank?

     #collaborator_string.split(",").map do |email|
     #@user = User.find_by_email(email_string)
    #Collaboration.find_or_create_by(user: user)
   #end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_wikis, dependent: :destroy, class_name: "Wiki"

  has_many :collaborations
  has_many :collaborating_wikis, through: :collaborations, class_name: "Wiki", source: :wiki

  before_save {self.email = email.downcase}
  after_initialize { self.role ||= :standard}

  enum role: [:standard, :premium, :admin]

  def downgrade
    self.standard!
    self.created_wikis.each { |wiki| wiki.make_public }
    save
  end

  def authorize_user
      wiki = Wiki.find(params[:id])

      unless current_user == wiki.creator || current_user.admin?
          flash[:alert] = "You must be an admin to do that."
          redirect_to wikis_path
      end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: :user_id

  has_many :collaborations
  has_many :collaborators, through: :collaborations, class_name: "User", source: :user
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 10 }, presence: true
  after_initialize { self.private ||= false}

  scope :visible_to, -> (user) { user.standard? ? where(private: false) : all }

  def make_public
    self.private = false
    save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  ## before_action :authenticate_user!
  def require_sign_in
      unless current_user
          flash[:alert] = "You must be logged in to do that"
          redirect_to new_user_session_path
      end
  end

  def authorized
    wiki = Wiki.find(params[:id])
    if wiki.private
      unless current_user && (current_user.admin? || wiki.creator == current_user || wiki.collaborators.include?(current_user))
        flash[:alert] = "You must be an authorized to do that."
        redirect_to wikis_path
      end
    end
  end

  def authorize_user
      wiki = Wiki.find(params[:id])
      unless current_user == wiki.creator || current_user.admin?
          flash[:alert] = "You must be an admin to do that."
          redirect_to wikis_path
      end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  DEFAULT_AMOUNT = 15_00
  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Upgrade to Premium - #{current_user.email}",
     amount: DEFAULT_AMOUNT
   }
  end

  def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: DEFAULT_AMOUNT,
     description: "Upgrade to Premium - #{current_user.email}",
     currency: 'usd'
   )

   flash[:notice] = "Thanks for your payment, #{current_user.email}! You will not regret it."
   current_user.premium!
   redirect_to wikis_path(current_user) # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end

 ##class Amount

   ##def self.default
     ##15_00
   ##end

 ##end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def remove
        @wiki = Wiki.find(params[:wiki_id])
        collaborator = @wiki.collaborators.find(params[:id])

        if @wiki.collaborators.delete(collaborator)
            flash[:notice] = "Collaborator deleted."
        else
            flash[:alert] = "Deleting collaborator failed."
        end
        redirect_to wikis_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def downgrade
   if current_user.downgrade
     flash[:notice] = "Premium membership cancelled successfully."
   else
     flash.now[:alert] = "There was an error cancelling your premium membership."
   end
  redirect_to wikis_path
 end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :require_sign_in, except: [:public, :show]
  before_action :authorized, only: [:show, :edit, :update]
  before_action :authorize_user, only: [:destroy]

  def index
    user = current_user
    @wikis = []
    all_wikis = policy_scope(Wiki)
    all_wikis.each do |wiki|
      if wiki.creator == user || wiki.collaborators.include?(user)
        @wikis << wiki # only show wikis they created, or private wikis they are a collaborator on
      end
    end
  end

  def public
    @wikis = policy_scope(Wiki)
  end

  def show
    @user = current_user
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.assign_attributes(wiki_params)
    @wiki.creator = current_user
    collaborator = User.find_by_email(params[:collaborator_email])

    if @wiki.save
      if collaborator
        @wiki.collaborators << collaborator
      end
      flash[:notice] = "\"#{@wiki.title}\" was created successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error creating the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    collaborator = User.find_by_email(params[:collaborator_email])

    if @wiki.save
      if collaborator && !@wiki.collaborators.include?(collaborator)
        @wiki.collaborators << collaborator
      end
      flash[:notice] = "\"#{@wiki.title}\" was updated successfully."
    else
      flash.now[:alert] = "There was an error updating the wiki."
    end
    render :edit
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
          flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
          redirect_to wikis_path
    else
          flash.now[:alert] = "There was an error deleting the wiki."
          render :show
    end
  end

  private

  def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    @markdown ||= Redcarpet::Markdown.new(renderer, extensions)
    @markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Upgrade to Premium for only $15!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborations/_form.html.erb
<div class="form-group">
  <%= label_tag "Collaborators" %>

  <%= render partial: "collaborations/list", locals: { collaborators: @wiki.collaborators } %>

  <%= text_field_tag 'collaborator_email',
                nil,
                class: 'form-control',
                placeholder: "Add a wiki collaborator by email" %>
</div>

app/views/collaborations/_list.html.erb
<div>
<% unless @wiki.collaborators.empty?  %>
  <% @wiki.collaborators.each do |collaborator| %>
  <%= collaborator.email %>
  <%= link_to "Remove Collaborator", remove_wiki_collaborator_path(@wiki, id: collaborator.id), method: :put, class: 'small', data: {confirm: 'Are you sure you want to delete this collaborator?'} %> <br/>
  <%  end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlocipediaProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link href="https://fonts.googleapis.com/css?family=Archivo+Black" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="navbar-collapse collapse">
     <ul class="nav nav-tabs navbar-left">
       <li class="logo"><%= link_to "BLOCIPEDIA", root_path %></li>
       <li><%= link_to "ALL WIKIS", public_wikis_path %></li>
       <li><%= link_to "MY WIKIS", wikis_path %></li>
    </ul>
     <% if user_signed_in? %>
      <ul class="nav nav-tabs navbar-right">
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">SIGNED IN AS: <strong><%= current_user.email %></strong> </a>
         <ul class="dropdown-menu">
           <li><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %></li>
           <% if current_user.standard? %>
              <li><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link'%></li>
           <% elsif current_user.premium? %>
              <li><%= link_to 'Cancel Premium Membership', downgrade_user_path(current_user), :class => 'navbar-link', method: :put, data: {confirm: 'Are you sure you want to cancel your premium membership? All of your private wikis will be made'}%></li>
           <% end %>
           <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
         </ul>
        </li>
     <% else %>
        <ul class="nav nav-tabs navbar-right">
          <li class="user-info"><%= link_to "SIGN UP", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li class="user-info"><%= link_to "SIGN IN", new_user_session_path, :class => 'navbar-link'  %></li>
     <% end %>
    </ul>
  </div>
  <div id="stripeModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">PREMIUM UPGRADE</h4>
      </div>
      <div class="modal-body">
           <h4>Upgrade to Premium for only $15!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

   <% if flash[:notice] %>
       <!-- <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div> -->
   <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
   <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
   <% end %>

 <%= yield %>

 </div>

</body>
</html>

app/views/welcome/index.html.haml
.main
  %p.heading BLOCIPEDIA
  %p.subheading Create and Share Markdown Wikis
  .why
    %h2 WHY BLOCIPEDIA
    .col-md-4
      %h3 Easy To Use
      %span.ion.ion-thumbsup
      %p BLOCIPEDIA is a simple and efficient way to create content accessible to anyone on the web. Simply sign up for an account and start creating shareable wikis today!
    .col-md-4
      %h3 Write in Markdown
      %span.ion.ion-social-markdown
      %p BLOCIPEDIA provides the ability for you to conveniently write content in Markdown.
    .col-md-4
      %h3 Share Ideas
      %span.ion.ion-android-bulb
      %p BLOCIPEDIA allows you to collaborate and share ideas, work, and knowledge with people around the world.
  .premium
    %h2 WHY PREMIUM
    .col-md-4
      %h3 Make Content Private
      %span.ion.ion-locked
      %p BLOCIPEDIA allows you to make your content private- where you have total control over who can access your wikis- with a premium membership.
    .col-md-4
      %h3 Add Collaborators
      %span.ion.ion-android-person-add
      %p A Premium Membership lets you add and remove collaborators as you see best for your private wikis.
    .col-md-4
      %h3 Access Your Work Anywhere
      %span.ion.ion-android-phone-portrait
      %p A Premium Membership provides support for you to access your wikis on any device.
  .start
    %h2= link_to "GET STARTED!", new_user_registration_path

app/views/wikis/_form.html.haml
.form-group
 = f.label :private, class: 'checkbox' do
  = f.check_box :private
  Private wiki

app/views/wikis/edit.html.haml
%h1 Edit Wiki
.row
 .col-md-4
  = form_for @wiki do |f|
   .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Enter wiki title"
   .form-group
    = f.label :body
    = f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body"
   - if (current_user.admin? || (@wiki.creator == current_user && current_user.premium?) || @wiki.collaborators.include?(current_user) )
    = render partial: 'form', locals: { f: f, wiki: @wiki }
    = render partial: 'collaborations/form', locals: { f: f, wiki: @wiki, collaborators: @wiki.collaborators }
   %p
    *You can use markdown in your wiki.</br>
    %small
     %a{:href => "http://daringfireball.net/projects/markdown/", :target =>"_blank"} Markdown Syntax
   .form-group
    = f.submit "Save", class: 'btn btn-success'
    = link_to "Back to Wikis", wikis_path, class: 'btn'
 .col-md-4
  = form_for @wiki do |f|
   .form-group
    = f.label :title
    = markdown(@wiki.title)
   .form-group
    = f.label :body
    = markdown(@wiki.body)

app/views/wikis/index.html.erb
<div class="public_wikis">
  <h1>MY WIKIS</h1>
  <div class="new-wiki-btn">
    <%= link_to "CREATE NEW WIKI", new_wiki_path %>
  </div>
  <div class="wikilist">
    <% @wikis.each do |wiki|%>
      <div class="wikis">
        <div class="col-md-8">
          <%= link_to markdown(wiki.title), wiki, class: 'wiki-title' %>
          <% if wiki.body.length > 100 %>
            <%= markdown(wiki.body)[0, 100] + "..."%>
          <% else %>
            <%= markdown(wiki.body)[0, 100] %>
          <% end %>
        </div>
        <div class="modify col-md-4">
          <%= link_to "EDIT", edit_wiki_path(wiki) %>
          <%= link_to "DELETE", [wiki], method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'} %>
        </div>
     </div>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.haml
%h1 New Wiki
.row
  .col-md-8
    = form_for @wiki do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', placeholder: "Enter wiki title"
      .form-group
        = f.label :body
        = f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body"
      - if current_user && current_user.premium?
        = render partial: 'form', locals: { f: f, wiki: @wiki }
        = render partial: 'collaborations/form', locals: { f: f, wiki: @wiki, collaborators: @wiki.collaborators }
      %p
        *You can use markdown in your wiki.
        %small
          %a{:href => "http://daringfireball.net/projects/markdown/", :target => "_blank"} Markdown Syntax
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/wikis/public.html.erb
<div class="public_wikis">
  <h1>ALL WIKIS</h1>
  <div class="new-wiki-btn">
    <%= link_to "CREATE NEW WIKI", new_wiki_path %>
  </div>
  <div class="wikilist">
    <% @wikis.each do |wiki|%>
      <div class="wikis">
        <div class="col-md-8">
          <%= link_to markdown(wiki.title), wiki, class: 'wiki-title' %>
          <% if wiki.body.length > 100 %>
            <%= markdown(wiki.body)[0, 100] + "..."%>
          <% else %>
            <%= markdown(wiki.body)[0, 100] %>
          <% end %>
        </div>
        <div class="modify col-md-4">
          <%= link_to "FOLLOW", edit_wiki_path(wiki) %>
          <!-- <%= link_to "DELETE", [wiki], method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'} %> -->
        </div>
     </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.haml
%h1= markdown(@wiki.title)
%h4= markdown(@wiki.body)

%div
 - if @wiki.private? && !@wiki.collaborators.empty?
  Collaborators:
  = render partial: "collaborations/list", locals: { collaborators: @wiki.collaborators }
%div
 = link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success'
 - if @user
  - if (@wiki.creator == @user) || @user.admin?
   = link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'}